version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: ["sh", "-c", "python init_db.py && python -m app"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  test:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - web
    command: ["pytest", "tests"]
